name: Create and publish kafka producer container image

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "main"

permissions: write-all

env:
  WORKING_DIRECTORY: flink_job
  REGISTRY: ghcr.io
  IMAGE_NAME: trino-query-executor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: mkdir staging && cp target/*.jar staging
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: actions/upload-artifact@v3
        with:
            name: Package
            path: ${{ env.WORKING_DIRECTORY }}/staging
            retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: ${{ env.WORKING_DIRECTORY }}/staging/*.jar
    