name: Create and publish flink job jar file

on:
  push:
    branches:
    - "**"
    paths:
      - flink_job/**
      - .github/workflows/build-and-publish-jar.yaml
  pull_request:
    branches:
    - "main"

permissions: write-all

env:
  WORKING_DIRECTORY: flink_job

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - uses: actions/upload-artifact@v3
        with:
            name: Package
            path: ${{ env.WORKING_DIRECTORY }}/build/libs
            retention-days: 1

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: ${{ env.WORKING_DIRECTORY }}//build/libs/*.jar
    