name: Publish JAR to GitHub Packages

on:
    push:
      branches:
      - "**"
      paths:
        - flink_job/**
        - .github/workflows/publish-jar-as-package.yaml
    pull_request:
      branches:
      - "main"

env:
  WORKING_DIRECTORY: flink_job

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}